name: YOLO Achievement

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print YOLO
        run: echo "YOLO! GitHub Actions is running."
